name: Build Headless Image

on:
  workflow_dispatch:

permissions:
  actions: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get current build ID
        id: build
        run: |
          BUILD_ID=$(
            curl --fail --silent --show-error --retry 3 \
              "https://api.steamcmd.net/v1/info/2519830" |
            jq -er '.data["2519830"].depots.branches["public"].buildid'
          )

          echo "Build ID: $BUILD_ID"
          echo "build_id=$BUILD_ID" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v7
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if current build is packaged
        id: check
        env:
          BUILD_ID: ${{ steps.}}
      - uses: docker/setup-buildx-action@v4
      - uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          pull: true
          no-cache: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/resonite-headless:latest
            ghcr.io/${{ github.repository_owner }}/resonite-headless:${{ steps.build.outputs.build_id }}
